name: Android build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["android"]
  pull_request:
    branches: ["android"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install .NET SDK 9.0.100-preview.6.24328.19
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-preview.6.24328.19

      - name: Fix gradlew permissions
        run: |
          chmod +x ./src/RyujinxAndroid/gradlew

      - name: Build APK for Android
        run: |
          cd ./src/RyujinxAndroid
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ryujinx-android
          path: ./src/RyujinxAndroid/app/build/outputs/apk/release/*.apk
