name: Build APK

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set to Java 17 as specified
          distribution: 'temurin'  # Specify the Java distribution to use

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/Android/Sdk/cmdline-tools
          mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk --licenses
          $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"  # Adjust for your target SDK

      - name: Set environment variables
        run: |
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV  # Set ANDROID_HOME
          echo "PATH=$PATH:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV  # Add platform-tools to PATH

      - name: Grant execute permissions to gradlew
        run: chmod +x src/RyujinxAndroid/gradlew  # Make the gradlew script executable

      - name: Build APK
        run: |
          cd src/RyujinxAndroid  # Navigate to the Android project directory
          ./gradlew assembleDebug  # Build the APK

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: src/RyujinxAndroid/app/build/outputs/apk/debug/*.apk  # Adjust if necessary
