name: Generated APK (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Required Libraries
        run: |
         sudo apt-get update
         sudo apt-get install -y \
         libc6-dev \
         zlib1g-dev \
         liblog4cxx-dev \
         libdl-dev \
         libgcc-9-dev

      # Install .NET SDK 9.0.100-preview.6.24328.19
      - name: Install .NET SDK 9.0.100-preview.6.24328.19
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100-preview.6.24328.19'

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./src/RyujinxAndroid/gradlew
      
      # Run Build Project
      - name: Build gradle project
        run: ./src/RyujinxAndroid/gradlew build -p src/RyujinxAndroid

      # Create APK Debug
      - name: Build APK debug project - ${{ env.main_project_module }} module
        run: ./src/RyujinxAndroid/gradlew assembleDebug -p src/RyujinxAndroid

      # Create APK Release
      - name: Build APK release project - ${{ env.main_project_module }} module
        run: ./src/RyujinxAndroid/gradlew assembleRelease -p src/RyujinxAndroid

      # Upload Artifact Build (APK Debug)
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK debug generated
          path: src/RyujinxAndroid/${{ env.main_project_module }}/build/outputs/apk/debug/

      # Upload Artifact Build (APK Release)
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK release generated
          path: src/RyujinxAndroid/${{ env.main_project_module }}/build/outputs/apk/release/
