name: Build APK

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-latest  # Change to Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set to Java 17 as specified
          distribution: 'temurin'  # Specify the Java distribution to use

      - name: Install Android SDK
        run: |
          choco install -y android-sdk
          echo "ANDROID_HOME=C:\ProgramData\chocolatey\lib\android-sdk\tools" >> $GITHUB_ENV
          echo "ANDROID_HOME=C:\ProgramData\chocolatey\lib\android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:C:\ProgramData\chocolatey\lib\android-sdk\platform-tools" >> $GITHUB_ENV
          echo "PATH=$PATH:C:\ProgramData\chocolatey\lib\android-sdk\tools" >> $GITHUB_ENV
          
      - name: Grant execute permissions to gradlew
        run: |
          icacls src\RyujinxAndroid\gradlew /grant Everyone:(RX)  # Grant read and execute permissions

      - name: Build APK
        run: |
          cd src/RyujinxAndroid  # Navigate to the Android project directory
          .\gradlew assembleDebug  # Build the APK

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: src/RyujinxAndroid\app\build\outputs\apk\debug\*.apk  # Adjust if necessary
